export enum ApiSection {
  Contacts = "contacts",
  Events = "events",
  Favorites = "favorites",
  Folders = "folders",
  Groups = "groups",
  Home = "home",
  ImageUrls = "imageurls",
  Reports = "reports",
  Search = "search",
  Server = "serverinfo",
  Sheets = "sheets",
  Sights = "sights",
  Templates = "templates",
  TemplatesPublic = "templatespublic",
  Token = "token",
  Users = "users",
  Webhooks = "webhooks",
  Workspaces = "workspaces",
}

export const apiUrlBySection = {
  [ApiSection.Contacts]: "contacts/",
  [ApiSection.Events]: "events/",
  [ApiSection.Favorites]: "favorites/",
  [ApiSection.Folders]: "folders/",
  [ApiSection.Groups]: "groups/",
  [ApiSection.Home]: "home/",
  [ApiSection.ImageUrls]: "imageurls/",
  [ApiSection.Reports]: "reports/",
  [ApiSection.Search]: "search/",
  [ApiSection.Server]: "serverinfo/",
  [ApiSection.Sheets]: "sheets/",
  [ApiSection.Sights]: "sights/",
  [ApiSection.Templates]: "templates/",
  [ApiSection.TemplatesPublic]: "templates/public",
  [ApiSection.Token]: "token",
  [ApiSection.Users]: "users/",
  [ApiSection.Webhooks]: "webhooks/",
  [ApiSection.Workspaces]: "workspaces/",
} as const;
