// Common User IDs
const TEST_USER_ID = 12345678;
const TEST_PLAN_ID = 1234567890123456;
const TEST_ACCOUNT_ID = 9876543210987654;

// Common Alternate Email ID
const TEST_ALTERNATE_EMAIL_ID = 9876543210987654;

// Common User Contact Information
const TEST_MOBILE_PHONE = '+1234567890';
const TEST_EMAIL = 'test.user@smartsheet.com';
const TEST_ALTERNATE_EMAIL = 'alternate.email@smartsheet.com';

// Common User Names
const TEST_FIRST_NAME = 'Test';
const TEST_LAST_NAME = 'User';
const TEST_NAME = 'Test User';

// Common User Timestamps
const TEST_CUSTOM_WELCOME_SCREEN_VIEWED = '2020-08-25T12:15:47Z';
const TEST_LAST_LOGIN = '2020-10-04T18:32:47Z';
const TEST_PROVISIONAL_EXPIRATION_DATE = '2026-12-13T12:17:52.525696Z';
const TEST_SEAT_TYPE_LAST_CHANGED_AT = '2025-01-01T00:00:00.123456789Z';

// Common Pagination Properties
const TEST_PAGE_NUMBER = 1;
const TEST_PAGE_SIZE = 100;
const TEST_TOTAL_PAGES = 1;
const TEST_TOTAL_COUNT = 1;

// Common User Properties
const TEST_SHEET_COUNT = 1;

// Common Profile Image Properties
const TEST_PROFILE_IMAGE_ID = 'u!1!nAtdn5RJB_o!k6_e_3h2R3w!wmYXPek-yVD';
const TEST_PROFILE_IMAGE_HEIGHT = 1050;
const TEST_PROFILE_IMAGE_WIDTH = 1050;

// Common Success Response Values
const TEST_SUCCESS_MESSAGE = 'SUCCESS';
const TEST_SUCCESS_RESULT_CODE = 0;

// Common Error Status Codes
const ERROR_500_STATUS_CODE = 500;
const ERROR_500_MESSAGE = 'Internal Server Error';
const ERROR_400_STATUS_CODE = 400;
const ERROR_400_MESSAGE = 'Malformed Request';

module.exports = {
  TEST_USER_ID,
  TEST_PLAN_ID,
  TEST_ACCOUNT_ID,
  TEST_ALTERNATE_EMAIL_ID,
  TEST_MOBILE_PHONE,
  TEST_EMAIL,
  TEST_ALTERNATE_EMAIL,
  TEST_FIRST_NAME,
  TEST_LAST_NAME,
  TEST_NAME,
  TEST_CUSTOM_WELCOME_SCREEN_VIEWED,
  TEST_LAST_LOGIN,
  TEST_PROVISIONAL_EXPIRATION_DATE,
  TEST_SEAT_TYPE_LAST_CHANGED_AT,
  TEST_PAGE_NUMBER,
  TEST_PAGE_SIZE,
  TEST_TOTAL_PAGES,
  TEST_TOTAL_COUNT,
  TEST_SHEET_COUNT,
  TEST_PROFILE_IMAGE_ID,
  TEST_PROFILE_IMAGE_HEIGHT,
  TEST_PROFILE_IMAGE_WIDTH,
  TEST_SUCCESS_MESSAGE,
  TEST_SUCCESS_RESULT_CODE,
  ERROR_500_STATUS_CODE,
  ERROR_500_MESSAGE,
  ERROR_400_STATUS_CODE,
  ERROR_400_MESSAGE
};
