const TEST_USER_ID = 12345678;
const TEST_PLAN_ID = 1234567890123456;
const TEST_SUCCESS_MESSAGE = 'SUCCESS';
const TEST_SUCCESS_RESULT_CODE = 0;

module.exports = {
  TEST_USER_ID,
  TEST_PLAN_ID,
  TEST_SUCCESS_MESSAGE,
  TEST_SUCCESS_RESULT_CODE
};
