name: Test Build

on: [pull_request, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js  
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run:  npm install jshint -g
      - name: Run jshint
        run: jshint -c .jshintrc lib/

  coverage:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Clone smartsheet/smartsheet-sdk-tests PUBLIC repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'smartsheet'
          repository: 'smartsheet-sdk-tests'
      - name: Setup mock API
        run: |
          smartsheet-sdk-tests/ci_scripts/install_wiremock.sh
          smartsheet-sdk-tests/ci_scripts/start_wiremock.sh
      - name: Run coverage on Node ${{ matrix.node-version }}
        run: npm run coverage
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: run-${{ matrix.node-version }}
          parallel: true

  finish:
    needs: coverage
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
